version: '3'

services:

  #SQL Service
  overlay-sql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
    - ./docker/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    networks:
      - overlay-network

  #Nginx Service
  overlay-webserver:
    image: nginx:alpine
    volumes:
      - ./:/var/www
      - ./docker/webserver/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"
    depends_on:
      - overlay-app
      - overlay-sql
    networks:
      - overlay-network

  #PHP Service
  overlay-app:
    build:
      context: ./
      dockerfile: docker/app/php/Dockerfile
    image: php
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - ./:/var/www
    ports:
      - "9001:9000"
    depends_on:
      - overlay-sql
    networks:
      - overlay-network


networks:
  overlay-network:
    driver: bridge
